package ax.xz.xed;

import java.util.Optional;

import static ax.xz.xed.xed_14.*;

public enum InstructionException {
	AMX_E1(XED_EXCEPTION_AMX_E1()),
	AMX_E1_EVEX(XED_EXCEPTION_AMX_E1_EVEX()),
	AMX_E2(XED_EXCEPTION_AMX_E2()),
	AMX_E2_EVEX(XED_EXCEPTION_AMX_E2_EVEX()),
	AMX_E3(XED_EXCEPTION_AMX_E3()),
	AMX_E3_EVEX(XED_EXCEPTION_AMX_E3_EVEX()),
	AMX_E4(XED_EXCEPTION_AMX_E4()),
	AMX_E5(XED_EXCEPTION_AMX_E5()),
	AMX_E6(XED_EXCEPTION_AMX_E6()),
	APX_EVEX_BMI(XED_EXCEPTION_APX_EVEX_BMI()),
	APX_EVEX_CCMP(XED_EXCEPTION_APX_EVEX_CCMP()),
	APX_EVEX_CET_WRSS(XED_EXCEPTION_APX_EVEX_CET_WRSS()),
	APX_EVEX_CET_WRUSS(XED_EXCEPTION_APX_EVEX_CET_WRUSS()),
	APX_EVEX_CFCMOV(XED_EXCEPTION_APX_EVEX_CFCMOV()),
	APX_EVEX_CMPCCXADD(XED_EXCEPTION_APX_EVEX_CMPCCXADD()),
	APX_EVEX_ENQCMD(XED_EXCEPTION_APX_EVEX_ENQCMD()),
	APX_EVEX_INT(XED_EXCEPTION_APX_EVEX_INT()),
	APX_EVEX_INVEPT(XED_EXCEPTION_APX_EVEX_INVEPT()),
	APX_EVEX_INVPCID(XED_EXCEPTION_APX_EVEX_INVPCID()),
	APX_EVEX_INVVPID(XED_EXCEPTION_APX_EVEX_INVVPID()),
	APX_EVEX_KMOV(XED_EXCEPTION_APX_EVEX_KMOV()),
	APX_EVEX_PP2(XED_EXCEPTION_APX_EVEX_PP2()),
	APX_EVEX_RAO_INT(XED_EXCEPTION_APX_EVEX_RAO_INT()),
	APX_LEGACY_JMPABS(XED_EXCEPTION_APX_LEGACY_JMPABS()),
	AVX512_E1(XED_EXCEPTION_AVX512_E1()),
	AVX512_E10(XED_EXCEPTION_AVX512_E10()),
	AVX512_E10NF(XED_EXCEPTION_AVX512_E10NF()),
	AVX512_E11(XED_EXCEPTION_AVX512_E11()),
	AVX512_E12(XED_EXCEPTION_AVX512_E12()),
	AVX512_E12NP(XED_EXCEPTION_AVX512_E12NP()),
	AVX512_E1NF(XED_EXCEPTION_AVX512_E1NF()),
	AVX512_E2(XED_EXCEPTION_AVX512_E2()),
	AVX512_E3(XED_EXCEPTION_AVX512_E3()),
	AVX512_E3NF(XED_EXCEPTION_AVX512_E3NF()),
	AVX512_E4(XED_EXCEPTION_AVX512_E4()),
	AVX512_E4NF(XED_EXCEPTION_AVX512_E4NF()),
	AVX512_E5(XED_EXCEPTION_AVX512_E5()),
	AVX512_E5NF(XED_EXCEPTION_AVX512_E5NF()),
	AVX512_E6(XED_EXCEPTION_AVX512_E6()),
	AVX512_E6NF(XED_EXCEPTION_AVX512_E6NF()),
	AVX512_E7NM(XED_EXCEPTION_AVX512_E7NM()),
	AVX512_E7NM128(XED_EXCEPTION_AVX512_E7NM128()),
	AVX512_E9NF(XED_EXCEPTION_AVX512_E9NF()),
	AVX512_K20(XED_EXCEPTION_AVX512_K20()),
	AVX512_K21(XED_EXCEPTION_AVX512_K21()),
	AVX_TYPE_1(XED_EXCEPTION_AVX_TYPE_1()),
	AVX_TYPE_11(XED_EXCEPTION_AVX_TYPE_11()),
	AVX_TYPE_12(XED_EXCEPTION_AVX_TYPE_12()),
	AVX_TYPE_14(XED_EXCEPTION_AVX_TYPE_14()),
	AVX_TYPE_2(XED_EXCEPTION_AVX_TYPE_2()),
	AVX_TYPE_2D(XED_EXCEPTION_AVX_TYPE_2D()),
	AVX_TYPE_3(XED_EXCEPTION_AVX_TYPE_3()),
	AVX_TYPE_4(XED_EXCEPTION_AVX_TYPE_4()),
	AVX_TYPE_4M(XED_EXCEPTION_AVX_TYPE_4M()),
	AVX_TYPE_5(XED_EXCEPTION_AVX_TYPE_5()),
	AVX_TYPE_5L(XED_EXCEPTION_AVX_TYPE_5L()),
	AVX_TYPE_6(XED_EXCEPTION_AVX_TYPE_6()),
	AVX_TYPE_7(XED_EXCEPTION_AVX_TYPE_7()),
	AVX_TYPE_8(XED_EXCEPTION_AVX_TYPE_8()),
	LEGACY_RAO_INT(XED_EXCEPTION_LEGACY_RAO_INT()),
	MMX_FP(XED_EXCEPTION_MMX_FP()),
	MMX_FP_16ALIGN(XED_EXCEPTION_MMX_FP_16ALIGN()),
	MMX_MEM(XED_EXCEPTION_MMX_MEM()),
	MMX_NOFP(XED_EXCEPTION_MMX_NOFP()),
	MMX_NOFP2(XED_EXCEPTION_MMX_NOFP2()),
	MMX_NOMEM(XED_EXCEPTION_MMX_NOMEM()),
	SSE_TYPE_1(XED_EXCEPTION_SSE_TYPE_1()),
	SSE_TYPE_2(XED_EXCEPTION_SSE_TYPE_2()),
	SSE_TYPE_2D(XED_EXCEPTION_SSE_TYPE_2D()),
	SSE_TYPE_3(XED_EXCEPTION_SSE_TYPE_3()),
	SSE_TYPE_4(XED_EXCEPTION_SSE_TYPE_4()),
	SSE_TYPE_4M(XED_EXCEPTION_SSE_TYPE_4M()),
	SSE_TYPE_5(XED_EXCEPTION_SSE_TYPE_5()),
	SSE_TYPE_7(XED_EXCEPTION_SSE_TYPE_7()),
	USER_MSR_EVEX(XED_EXCEPTION_USER_MSR_EVEX()),
	USER_MSR_LEGACY(XED_EXCEPTION_USER_MSR_LEGACY()),
	USER_MSR_VEX(XED_EXCEPTION_USER_MSR_VEX());

	private final int xedEnum;

	InstructionException(int xedEnum) {
		this.xedEnum = xedEnum;
	}

	public static Optional<InstructionException> from(int xedEnum) {
		if (xedEnum == 0) {
			return Optional.empty();
		}

		var result = values()[xedEnum - 1];
		if (result.xedEnum != xedEnum) {
			throw new AssertionError("mismatched enum: " + xedEnum + ", " + result);
		}

		return Optional.of(result);
	}
}
