package ax.xz.fuzz.encoding;

public enum InstructionFlag {
	CPU_STATE_CR,
	CPU_STATE_CW,
	FAR_BRANCH,
	FPU_STATE_CR,
	FPU_STATE_CW,
	IGNORE_MODRM_MOD,
	IS_GATHER,
	NEAR_BRANCH,
	NO_SOURCE_DEST_MATCH,
	NO_SOURCE_SOURCE_MATCH,
	PROTECTED_MODE,
	SHORT_BRANCH,
	XMM_STATE_CR,
	XMM_STATE_CW
}
